name: Create Master Playlist

on:
  workflow_dispatch:
    inputs:
      uuid:
        description: "UUID of processed video folder (e.g., uuid_abc123)"
        required: true

jobs:
  masterPlaylist:
    runs-on: ubuntu-latest
    env:
      FTP_HOST: ${{ secrets.FTP_HOST }}
      FTP_USER: ${{ secrets.FTP_USER }}
      FTP_PASS: ${{ secrets.FTP_PASS }}
      FTP_BASE_URL: "/public_html/videos"
      DOMAIN: "https://kuntalworks.com"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install lftp and openssl
        run: sudo apt update && sudo apt install -y lftp openssl

      - name: Generate encryption key
        run: |
          mkdir -p encryption
          openssl rand 16 > encryption/key.bin

      - name: Create master playlist
        run: |
          mkdir -p work
          cat > work/master.m3u8 <<EOF
          #EXTM3U
          #EXT-X-VERSION:3
          #EXT-X-STREAM-INF:BANDWIDTH=800000,RESOLUTION=854x480
          480p/playlist.m3u8
          #EXT-X-STREAM-INF:BANDWIDTH=1400000,RESOLUTION=1280x720
          720p/playlist.m3u8
          #EXT-X-STREAM-INF:BANDWIDTH=3000000,RESOLUTION=1920x1080
          1080p/playlist.m3u8
          EOF

      - name: Upload master.m3u8 and key.key to FTP
        run: |
          echo "Uploading master playlist and key to FTP..."
          lftp -u "$FTP_USER","$FTP_PASS" $FTP_HOST <<EOF
          set ftp:ssl-allow no
          mkdir -p $FTP_BASE_URL/${{ github.event.inputs.uuid }}/segments
          put work/master.m3u8 -o $FTP_BASE_URL/${{ github.event.inputs.uuid }}/segments/master.m3u8
          put encryption/key.bin -o $FTP_BASE_URL/${{ github.event.inputs.uuid }}/segments/key.key
          bye
          EOF

      - name: Summary
        run: echo "✅ Master playlist and key uploaded successfully!"
